import test from 'node:test';import assert from 'node:assert/strict';import handler,{normalizePhone} from '../netlify/functions/field-contractor-invite.js';
const env={SUPABASE_URL:'https://db.test',SUPABASE_PUBLISHABLE_KEY:'public',SUPABASE_SERVICE_ROLE_KEY:'test-admin',URL:'https://operations.test',TWILIO_ACCOUNT_SID:'test-sid',TWILIO_AUTH_TOKEN:'test-token',TWILIO_PHONE_NUMBER:'+14085550000'};globalThis.Netlify={env:{get:n=>env[n]}};
const req=(body,token=true)=>new Request('https://operations.test/api',{method:'POST',headers:token?{authorization:'Bearer fixture'}:{},body:JSON.stringify(body)}),res=(data,status=200)=>new Response(JSON.stringify(data),{status});
async function mocked(fn,work){const orig=globalThis.fetch;globalThis.fetch=fn;try{await work();}finally{globalThis.fetch=orig;}}
const person={profile_id:'p',invitation_id:null,email:'test@example.com',phone:'+14085551234',email_pending:true,sms_pending:true};
const base={action:'invite',company_id:'c',email:person.email,phone:person.phone,name:'Example'};
test('normalizes US and international phones',()=>{assert.equal(normalizePhone('(408) 555-1234'),person.phone);assert.equal(normalizePhone('+442079460123'),'+442079460123');assert.throws(()=>normalizePhone('bad'));});
test('no authenticated caller means no messages',async()=>{await mocked(()=>{throw Error('should not call')},async()=>assert.equal((await handler(req({},false))).status,401));});
test('denied owner RPC never reaches either provider',async()=>{let calls=0;await mocked(async()=>{calls++;return res({message:'Owner access required'},403)},async()=>{assert.equal((await handler(req({...base,channels:['email','sms']}))).status,400);assert.equal(calls,1)});});
test('email plus SMS tracked independently; trusted redirect only',async()=>{const calls=[];await mocked(async(url,o)=>{calls.push({url,body:o.body});if(url.includes('invite_contractor_channels'))return res('p');if(url.includes('pending_contractor_delivery'))return res([person]);if(url.includes('twilio'))return res({status:'queued',sid:'sid'});return res({});},async()=>{const d=await (await handler(req({...base,channels:['email','sms'],siteUrl:'https://attacker.test'}))).json();assert.deepEqual(d.sent,{email:1,sms:1});assert(!calls.some(x=>x.url.includes('attacker')));assert(calls.some(x=>x.url.includes(encodeURIComponent('https://la-contractor-operations.k-aslanpour.chatgpt.site/login.html'))));assert.equal(calls.filter(x=>x.url.includes('record_contractor_delivery')).length,2)});});
test('SMS-only needs no email request',async()=>{let emails=0;await mocked(async(url)=>{if(url.includes('/auth/'))emails++;if(url.includes('invite_contractor_channels'))return res('p');if(url.includes('pending_contractor_delivery'))return res([{...person,email:null,email_pending:false}]);return res({status:'queued'});},async()=>{const d=await(await handler(req({...base,email:null,channels:['sms']}))).json();assert.deepEqual(d.sent,{email:0,sms:1});assert.equal(emails,0)});});
test('failed SMS does not erase successful email and retries skip accepted email',async()=>{let emailCalls=0;await mocked(async(url)=>{if(url.includes('pending_contractor_delivery'))return res([{...person,email_pending:false}]);if(url.includes('/auth/'))emailCalls++;if(url.includes('twilio'))return res({message:'Rejected'},400);return res({});},async()=>{const d=await(await handler(req({action:'retry_bid',package_id:'bid',channels:['email','sms']}))).json();assert.deepEqual(d.sent,{email:0,sms:0});assert.equal(emailCalls,0);assert.equal(d.failures.length,1)});});

test('void database success is recorded without a false delivery warning',async()=>{await mocked(async(url)=>{if(url.includes('invite_contractor_channels'))return res('p');if(url.includes('pending_contractor_delivery'))return res([person]);if(url.includes('record_contractor_delivery'))return new Response(null,{status:204});return res({});},async()=>{const d=await(await handler(req({...base,channels:['email']}))).json();assert.deepEqual(d.sent,{email:1,sms:0});assert.deepEqual(d.failures,[]);});});
test('SMTP error remains visible when recording failure returns empty success',async()=>{await mocked(async(url)=>{if(url.includes('invite_contractor_channels'))return res('p');if(url.includes('pending_contractor_delivery'))return res([person]);if(url.includes('record_contractor_delivery'))return new Response(null,{status:204});return res({msg:'Error sending invite email'},500);},async()=>{const d=await(await handler(req({...base,channels:['email']}))).json();assert.equal(d.sent.email,0);assert.equal(d.failures.length,1);assert.match(d.failures[0],/Error sending invite email/);});});
